### ISSUE TITLE
Error, retrying in 3 seconds. -1 retries left.

### ISSUE THREAD

**Issue by lim3ra** [supersu-man/spotify-playlist-downloader#8]
Hi,

this is the only message I can see on Pixel 4, Android 11.0

"Error, retrying in 3 seconds. -1 retries left."

Any additional config is required for this to work?

**Comment by supersu-man** [comment]
Will check the issue. Meanwhile check out [Hymn](https://github.com/supersu-man/hymn)

**Comment by supersu-man** [comment]
A new update is out, closing this issue.
