### ISSUE TITLE
Not downloading

### ISSUE THREAD

**Issue by mohidxh** [supersu-man/spotify-playlist-downloader#9]
I dropped the link of my Spotify playlist, pressed download, it fetched all the songs,  it was showing 132/132 and after that there's nothing i can do. I can't find the downloaded songs in my storage, and if i press the download button one again, it starts getting all the songs again.

**Comment by supersu-man** [comment]
> I can't find the downloaded songs in my storage

Did you check Downloads/spd folder ?

**Comment by mohidxh** [comment]
Yes i did. 
![Screenshot_2024-10-30-23-40-33-725_dev sumanth spd](https://github.com/user-attachments/assets/e9459d3c-4489-453e-994f-ff3c289be3e5)
![Screenshot_2024-10-30-23-40-39-015_com mi android globalFileexplorer](https://github.com/user-attachments/assets/0fe7ac03-0a06-44ed-9c3d-e8f86f70cf55)

**Comment by mohidxh** [comment]
If i press the download button again it starts downloading again from 1

**Comment by supersu-man** [comment]
Fixed in [v1.7.1](https://github.com/supersu-man/spotify-playlist-downloader/releases/tag/v1.7.1)
